# Generated by Django 6.0.3 on 2026-04-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_arrivals', models.IntegerField()),
                ('monthly_visits', models.IntegerField()),
                ('top_destinations', models.IntegerField()),
                ('satisfaction', models.FloatField()),
            ],
        ),
    ]
