import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_reference_tables"),
    ]

    operations = [
        migrations.RenameField(
            model_name="touristrecord",
            old_name="country_id",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="touristrecord",
            old_name="region_id",
            new_name="region",
        ),
        migrations.RenameField(
            model_name="touristrecord",
            old_name="province_id",
            new_name="province",
        ),
        migrations.RenameField(
            model_name="touristrecord",
            old_name="itinerary_id",
            new_name="itinerary",
        ),
        migrations.RenameField(
            model_name="touristrecord",
            old_name="resort_id",
            new_name="resort",
        ),
        migrations.RenameField(
            model_name="touristrecord",
            old_name="travel_mode_id",
            new_name="travel_mode",
        ),
        migrations.RenameField(
            model_name="touristrecord",
            old_name="boat_type_id",
            new_name="boat_type",
        ),
        migrations.RenameField(
            model_name="touristrecord",
            old_name="visit_purpose_id",
            new_name="visit_purpose",
        ),
        migrations.AlterField(
            model_name="touristrecord",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tourist_records",
                to="api.country",
            ),
        ),
        migrations.AlterField(
            model_name="touristrecord",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tourist_records",
                to="api.region",
            ),
        ),
        migrations.AlterField(
            model_name="touristrecord",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tourist_records",
                to="api.province",
            ),
        ),
        migrations.AlterField(
            model_name="touristrecord",
            name="itinerary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tourist_records",
                to="api.itinerary",
            ),
        ),
        migrations.AlterField(
            model_name="touristrecord",
            name="resort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tourist_records",
                to="api.resort",
            ),
        ),
        migrations.AlterField(
            model_name="touristrecord",
            name="travel_mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tourist_records",
                to="api.travelmode",
            ),
        ),
        migrations.AlterField(
            model_name="touristrecord",
            name="boat_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tourist_records",
                to="api.boattype",
            ),
        ),
        migrations.AlterField(
            model_name="touristrecord",
            name="visit_purpose",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tourist_records",
                to="api.visitpurpose",
            ),
        ),
    ]
