# Generated by Django 6.0.4 on 2026-05-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feedbackentry_tourismsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanitaryBusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('inspection_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SanitaryEstablishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('owner_name', models.CharField(max_length=160)),
                ('permit_size', models.CharField(choices=[('sp', 'SP'), ('large', 'Large')], default='sp', max_length=20)),
                ('barangay', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=240)),
                ('contact_number', models.CharField(blank=True, max_length=60)),
                ('has_permit', models.BooleanField(default=True)),
                ('permit_number', models.CharField(blank=True, max_length=80)),
                ('permit_issued_date', models.DateField(blank=True, null=True)),
                ('permit_expiry_date', models.DateField(blank=True, null=True)),
                ('compliance_status', models.CharField(choices=[('good_standing', 'Good Standing'), ('upcoming', 'Upcoming'), ('for_completion', 'For Completion'), ('violation', 'Violation'), ('no_permit', 'No Permit')], default='good_standing', max_length=30)),
                ('permit_status', models.CharField(choices=[('active', 'Active'), ('renewal_due', 'Active - Renewal Due'), ('conditional', 'Conditional'), ('suspended', 'Suspended'), ('no_permit', 'No Permit')], default='active', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='api.sanitarybusinesstype')),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='SanitaryInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(max_length=160)),
                ('inspection_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('status_after_inspection', models.CharField(choices=[('good_standing', 'Good Standing'), ('upcoming', 'Upcoming'), ('for_completion', 'For Completion'), ('violation', 'Violation'), ('no_permit', 'No Permit')], default='good_standing', max_length=30)),
                ('photo_documentation', models.CharField(blank=True, max_length=255)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='api.sanitaryestablishment')),
            ],
            options={
                'ordering': ['-inspection_date', 'establishment__business_name'],
            },
        ),
        migrations.CreateModel(
            name='SanitaryInspectionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=180)),
                ('is_complied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='api.sanitaryinspection')),
            ],
            options={
                'ordering': ['requirement_name'],
            },
        ),
        migrations.CreateModel(
            name='SanitaryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_size', models.CharField(choices=[('sp', 'SP'), ('large', 'Large')], max_length=20)),
                ('requirement_name', models.CharField(max_length=180)),
                ('is_required', models.BooleanField(default=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.sanitarybusinesstype')),
            ],
            options={
                'ordering': ['business_type__name', 'permit_size', 'requirement_name'],
                'unique_together': {('business_type', 'permit_size', 'requirement_name')},
            },
        ),
    ]
