# Generated by Django 6.0.4 on 2026-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sanitarybusinesstype_sanitaryestablishment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdSanitationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_code', models.CharField(max_length=30, unique=True)),
                ('household_head', models.CharField(max_length=160)),
                ('barangay', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
                ('toilet_type', models.CharField(choices=[('water_sealed', 'Water-Sealed'), ('pour_flush', 'Pour-Flush'), ('pit_latrine', 'Pit Latrine'), ('none', 'None')], default='water_sealed', max_length=30)),
                ('water_level', models.CharField(choices=[('level_1', 'Level I'), ('level_2', 'Level II'), ('level_3', 'Level III')], default='level_3', max_length=30)),
                ('water_source', models.CharField(blank=True, max_length=120)),
                ('waste_disposal', models.CharField(choices=[('collected', 'Collected by LGU'), ('composted', 'Composted'), ('burned', 'Burned'), ('dumped', 'Dumped')], default='collected', max_length=30)),
                ('status', models.CharField(choices=[('good_standing', 'Good Standing'), ('for_completion', 'For Completion'), ('violation', 'Violation')], default='good_standing', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('last_survey_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['barangay', 'household_head'],
            },
        ),
    ]
