# Generated by Django 6.0.4 on 2026-05-10 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_householdsanitationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResortMonthlyArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025)),
                ('month', models.PositiveIntegerField()),
                ('total_arrivals', models.PositiveIntegerField(default=0)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_monthly_arrivals', to='api.resort')),
            ],
            options={
                'ordering': ['year', 'month', 'resort__resort_name'],
                'unique_together': {('resort', 'year', 'month')},
            },
        ),
    ]
