# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristrecord",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="touristrecord",
            name="consent_confirmed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="touristrecord",
            name="country_of_origin",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="touristrecord",
            name="boat_capacity_fare",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="touristrecord",
            name="parking_space",
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
