# Generated by Codex on 2026-05-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_touristrecord_online_booking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="province",
            name="code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="province",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provinces",
                to="api.region",
            ),
        ),
    ]
