# Generated by Codex on 2026-05-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_region_province_codes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TourismSettings",
        ),
    ]
