# Generated by Django 6.0.4 on 2026-05-18 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_tourismsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanitaryPermitRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_id', models.CharField(max_length=40, unique=True)),
                ('permit_number', models.CharField(max_length=80)),
                ('permit_type', models.CharField(default='Sanitary Permit', max_length=80)),
                ('expiration_date', models.DateField()),
                ('stage', models.CharField(choices=[('notice_sent', 'Notice Sent'), ('application_filed', 'Application Filed'), ('requirements_review', 'Requirements Review'), ('inspection_scheduled', 'Inspection Scheduled'), ('payment_pending', 'Payment Pending'), ('approved', 'Approved'), ('released', 'Released'), ('lapsed', 'Lapsed')], default='notice_sent', max_length=40)),
                ('progress', models.PositiveIntegerField(default=14)),
                ('renewal_fee', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial')], default='unpaid', max_length=20)),
                ('submitted_requirements', models.JSONField(blank=True, default=list)),
                ('inspection_status', models.CharField(blank=True, max_length=160)),
                ('photo_documentation', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_renewals', to='api.sanitaryestablishment')),
            ],
            options={
                'ordering': ['expiration_date', 'renewal_id'],
            },
        ),
    ]
