# Generated by Django 6.0.4 on 2026-05-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sanitarypermitrenewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanitaryComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=40, unique=True)),
                ('complainant_name', models.CharField(blank=True, max_length=160)),
                ('contact_number', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(max_length=120)),
                ('barangay', models.CharField(max_length=120)),
                ('reported_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='api.sanitaryestablishment')),
            ],
            options={
                'ordering': ['-reported_date', '-id'],
            },
        ),
    ]
