# Generated by Django 6.0.4 on 2026-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sanitarycomplaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('municipality', models.CharField(default='Mauban', max_length=120)),
                ('province', models.CharField(default='Quezon', max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Barangays',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
