# Generated by Django 6.0.4 on 2026-05-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristrecord',
            name='contact_number',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
