# Generated by Django 6.0.4 on 2026-05-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_touristrecord_contact_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='touristrecord',
            index=models.Index(fields=['status', 'arrival_date'], name='tourist_status_arrival_idx'),
        ),
        migrations.AddIndex(
            model_name='touristrecord',
            index=models.Index(fields=['arrival_date'], name='tourist_arrival_idx'),
        ),
        migrations.AddIndex(
            model_name='touristrecord',
            index=models.Index(fields=['resort', 'arrival_date'], name='tourist_resort_arrival_idx'),
        ),
        migrations.AddIndex(
            model_name='touristrecord',
            index=models.Index(fields=['region'], name='tourist_region_idx'),
        ),
        migrations.AddIndex(
            model_name='touristrecord',
            index=models.Index(fields=['province'], name='tourist_province_idx'),
        ),
    ]
