# Generated by Django 6.0.4 on 2026-06-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_annual_sanitary_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanitaryrequirement',
            options={'ordering': ['business_type__name', 'permit_size', 'id']},
        ),
    ]
