# Generated by Django 6.0.4 on 2026-06-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_sanitaryrequirement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitarycomplaint',
            name='assigned_inspector',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sanitarycomplaint',
            name='inspection_notify_reporter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sanitarycomplaint',
            name='inspection_schedule_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sanitarycomplaint',
            name='inspection_scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanitarycomplaint',
            name='inspection_scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sanitarycomplaint',
            index=models.Index(fields=['inspection_scheduled_date'], name='san_comp_sched_idx'),
        ),
    ]
