# Generated by Django 6.0.4 on 2026-06-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_sanitarycomplaint_assigned_inspector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touristrecord',
            options={'ordering': ['-updated_at', '-arrival_date', 'survey_id']},
        ),
    ]
