# Generated by Django 6.0.4 on 2026-06-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_touristrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackentry',
            options={'ordering': ['-id']},
        ),
    ]
