# Generated by Django 6.0.4 on 2026-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_feedbackentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanitaryestablishment',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AddField(
            model_name='touristrecord',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='touristrecord',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='touristrecord',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
