# Generated by Django 6.0.4 on 2026-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_sanitaryestablishment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackentry',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resort',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
