# Generated by Django 6.0.4 on 2026-09-04 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_feedbackentry_photos_resort_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sanitaryestablishment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanitary_establishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sanitarycomplaint',
            name='photo_documentation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('tourism', 'Tourism Office'), ('sanitation', 'Sanitary Section'), ('establishment', 'Establishment Owner')], default='tourism', max_length=20),
        ),
    ]
