# Generated by Django 6.0.4 on 2026-09-11 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_resort_user_sanitaryestablishment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('permit_due', 'Permit Due'), ('inspection_due', 'Inspection Due'), ('violation_alert', 'Violation Alert'), ('public_advisory', 'Public Advisory'), ('system', 'System')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('module', models.CharField(choices=[('sanitation', 'Sanitation'), ('tourism', 'Tourism'), ('general', 'General')], max_length=20)),
                ('audience_type', models.CharField(choices=[('user', 'User'), ('role', 'Role'), ('public', 'Public')], max_length=20)),
                ('target_role', models.CharField(blank=True, choices=[('admin', 'System Admin'), ('tourism', 'Tourism Office'), ('sanitation', 'Sanitary Section'), ('establishment', 'Establishment Owner')], max_length=20)),
                ('related_model', models.CharField(blank=True, max_length=60)),
                ('related_object_id', models.CharField(blank=True, max_length=60)),
                ('related_due_date', models.DateField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['audience_type', 'target_role', 'is_read', '-created_at'], name='notif_aud_role_read_idx'), models.Index(fields=['recipient_user', 'is_read', '-created_at'], name='notif_user_read_idx')],
            },
        ),
    ]
