# Generated by Django 6.0.4 on 2026-09-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_role',
            field=models.CharField(blank=True, choices=[('admin', 'System Admin'), ('tourism', 'Tourism Office'), ('sanitation', 'Sanitary Section'), ('establishment', 'Establishment Owner'), ('tourist', 'Tourist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('tourism', 'Tourism Office'), ('sanitation', 'Sanitary Section'), ('establishment', 'Establishment Owner'), ('tourist', 'Tourist')], default='tourism', max_length=20),
        ),
    ]
