# Generated by Django 6.0.4 on 2026-09-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_ambulant_food_vendor_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitaryestablishment',
            name='compliance_status',
            field=models.CharField(choices=[('not_yet_inspected', 'Not Yet Inspected'), ('good_standing', 'Good Standing'), ('upcoming', 'Upcoming'), ('for_completion', 'For Completion'), ('violation', 'Violation'), ('no_permit', 'No Permit')], default='not_yet_inspected', max_length=30),
        ),
    ]
