# Generated by Django 6.0.4 on 2026-09-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_create_throttle_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitarycomplaint',
            name='location_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
