# Generated by Django 6.0.4 on 2026-09-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_sanitarycomplaint_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitarycomplaint',
            name='client_submission_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
