# Generated by Django 6.0.4 on 2026-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_sanitaryestablishment_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdsanitationrecord',
            name='septic_tank_type',
            field=models.CharField(blank=True, choices=[('septic_tank', 'Septic tank'), ('bottomless', 'Bottomless'), ('vault_sealed', 'Vault-sealed')], max_length=30, null=True),
        ),
    ]
