# Generated by Django 6.0.4 on 2026-09-28 12:11

import api.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_sanitaryestablishment_tracking_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#2FA34A', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('mobile_follows_web', models.BooleanField(default=True)),
                ('mobile_primary_color', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a colour as #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('saved_colors', models.JSONField(default=api.models.default_tourism_saved_colors)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourism_theme_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
