# Generated by Django 6.0.4 on 2026-10-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_householdsanitationrecord_septic_tank_type'),
        ('api', '0041_tourismthemesetting'),
    ]

    operations = [
    ]
