# Generated by Django 6.0.4 on 2026-10-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_consolidate_boat_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristrecord',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tourist_records', to='api.province'),
        ),
        migrations.AlterField(
            model_name='touristrecord',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tourist_records', to='api.region'),
        ),
    ]
