INITIAL_TOURIST_RECORDS = [
    {
        "survey_id": "SURV-2026-001",
        "email": "maria.ramos@example.com",
        "full_name": "Maria Teresa Ramos",
        "contact_number": "09171234567",
        "country_id": 1,
        "region_id": 1,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 2,
        "maubanin_count": 1,
        "total_visitors": 3,
        "total_male": 1,
        "total_female": 2,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 3,
        "age_60_above": 0,
        "arrival_date": "2026-04-11",
        "itinerary_id": 1,
        "resort_id": 1,
        "travel_mode_id": 4,
        "boat_type_id": 1,
        "visit_purpose_id": 1,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-002",
        "email": "ethan.lee@example.com",
        "full_name": "Ethan Lee",
        "contact_number": "+63 917 884 2201",
        "country_id": 3,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 2,
        "filipino_count": 1,
        "maubanin_count": 0,
        "total_visitors": 3,
        "total_male": 2,
        "total_female": 1,
        "special_group_count": 1,
        "age_0_7": 0,
        "age_8_59": 3,
        "age_60_above": 0,
        "arrival_date": "2026-04-11",
        "itinerary_id": 1,
        "resort_id": 4,
        "travel_mode_id": 2,
        "boat_type_id": 2,
        "visit_purpose_id": 1,
        "status": "pending",
    },
    {
        "survey_id": "SURV-2026-003",
        "email": "villanueva.family@example.com",
        "full_name": "Jonathan Villanueva",
        "contact_number": "09984561230",
        "country_id": 1,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 0,
        "filipino_count": 4,
        "maubanin_count": 0,
        "total_visitors": 4,
        "total_male": 2,
        "total_female": 2,
        "special_group_count": 2,
        "age_0_7": 1,
        "age_8_59": 3,
        "age_60_above": 0,
        "arrival_date": "2026-04-10",
        "itinerary_id": 2,
        "resort_id": 2,
        "travel_mode_id": 1,
        "boat_type_id": 1,
        "visit_purpose_id": 1,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-004",
        "email": "clare.garcia@example.com",
        "full_name": "Clare Garcia",
        "contact_number": "09170112233",
        "country_id": 1,
        "region_id": 1,
        "province_id": 2,
        "foreigner_count": 0,
        "filipino_count": 2,
        "maubanin_count": 0,
        "total_visitors": 2,
        "total_male": 0,
        "total_female": 2,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 1,
        "age_60_above": 1,
        "arrival_date": "2026-04-09",
        "itinerary_id": 4,
        "resort_id": 5,
        "travel_mode_id": 3,
        "boat_type_id": 3,
        "visit_purpose_id": 3,
        "status": "no_show",
    },
    {
        "survey_id": "SURV-2026-005",
        "email": "akira.tanaka@example.com",
        "full_name": "Akira Tanaka",
        "contact_number": "+63 918 551 9801",
        "country_id": 5,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 1,
        "filipino_count": 1,
        "maubanin_count": 0,
        "total_visitors": 2,
        "total_male": 1,
        "total_female": 1,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 2,
        "age_60_above": 0,
        "arrival_date": "2026-04-08",
        "itinerary_id": 3,
        "resort_id": 6,
        "travel_mode_id": 2,
        "boat_type_id": 3,
        "visit_purpose_id": 3,
        "status": "pending",
    },
    {
        "survey_id": "SURV-2026-006",
        "email": "reyes.team@example.com",
        "full_name": "Camille Reyes",
        "contact_number": "09271114455",
        "country_id": 1,
        "region_id": 1,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 5,
        "maubanin_count": 2,
        "total_visitors": 7,
        "total_male": 4,
        "total_female": 3,
        "special_group_count": 1,
        "age_0_7": 1,
        "age_8_59": 6,
        "age_60_above": 0,
        "arrival_date": "2026-04-07",
        "itinerary_id": 1,
        "resort_id": 1,
        "travel_mode_id": 4,
        "boat_type_id": 1,
        "visit_purpose_id": 4,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-007",
        "email": "daniel.santos@example.com",
        "full_name": "Daniel Santos",
        "contact_number": "09189998877",
        "country_id": 1,
        "region_id": 3,
        "province_id": 5,
        "foreigner_count": 0,
        "filipino_count": 3,
        "maubanin_count": 0,
        "total_visitors": 3,
        "total_male": 2,
        "total_female": 1,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 3,
        "age_60_above": 0,
        "arrival_date": "2026-04-06",
        "itinerary_id": 2,
        "resort_id": 3,
        "travel_mode_id": 1,
        "boat_type_id": 2,
        "visit_purpose_id": 2,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-008",
        "email": "australia.group@example.com",
        "full_name": "Sophie Martin",
        "contact_number": "+63 917 781 9931",
        "country_id": 4,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 4,
        "filipino_count": 1,
        "maubanin_count": 0,
        "total_visitors": 5,
        "total_male": 2,
        "total_female": 3,
        "special_group_count": 1,
        "age_0_7": 0,
        "age_8_59": 5,
        "age_60_above": 0,
        "arrival_date": "2026-04-05",
        "itinerary_id": 1,
        "resort_id": 2,
        "travel_mode_id": 2,
        "boat_type_id": 2,
        "visit_purpose_id": 1,
        "status": "pending",
    },
    {
        "survey_id": "SURV-2026-009",
        "email": "local.hikers@example.com",
        "full_name": "Arvin Mendoza",
        "contact_number": "09081239876",
        "country_id": 1,
        "region_id": 1,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 2,
        "maubanin_count": 3,
        "total_visitors": 5,
        "total_male": 3,
        "total_female": 2,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 4,
        "age_60_above": 1,
        "arrival_date": "2026-04-04",
        "itinerary_id": 3,
        "resort_id": 6,
        "travel_mode_id": 1,
        "boat_type_id": 3,
        "visit_purpose_id": 1,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-010",
        "email": "school.trip@example.com",
        "full_name": "Helen de la Cruz",
        "contact_number": "09195550066",
        "country_id": 1,
        "region_id": 4,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 18,
        "maubanin_count": 0,
        "total_visitors": 18,
        "total_male": 8,
        "total_female": 10,
        "special_group_count": 3,
        "age_0_7": 0,
        "age_8_59": 18,
        "age_60_above": 0,
        "arrival_date": "2026-04-03",
        "itinerary_id": 4,
        "resort_id": 5,
        "travel_mode_id": 3,
        "boat_type_id": 3,
        "visit_purpose_id": 3,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-011",
        "email": "weekend.barkada@example.com",
        "full_name": "Paolo Navarro",
        "contact_number": "09183334455",
        "country_id": 1,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 0,
        "filipino_count": 6,
        "maubanin_count": 0,
        "total_visitors": 6,
        "total_male": 3,
        "total_female": 3,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 6,
        "age_60_above": 0,
        "arrival_date": "2026-04-02",
        "itinerary_id": 2,
        "resort_id": 3,
        "travel_mode_id": 1,
        "boat_type_id": 1,
        "visit_purpose_id": 1,
        "status": "pending",
    },
    {
        "survey_id": "SURV-2026-012",
        "email": "mauban.office@example.com",
        "full_name": "Rina Castillo",
        "contact_number": "09171116677",
        "country_id": 1,
        "region_id": 1,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 2,
        "maubanin_count": 4,
        "total_visitors": 6,
        "total_male": 2,
        "total_female": 4,
        "special_group_count": 1,
        "age_0_7": 1,
        "age_8_59": 4,
        "age_60_above": 1,
        "arrival_date": "2026-04-01",
        "itinerary_id": 4,
        "resort_id": 5,
        "travel_mode_id": 1,
        "boat_type_id": 3,
        "visit_purpose_id": 5,
        "status": "arrived",
    },
]

REFERENCE_TABLES = {
    "countries": [
        {"id": 1, "name": "Philippines", "type": "local"},
        {"id": 2, "name": "United States", "type": "foreign"},
        {"id": 3, "name": "South Korea", "type": "foreign"},
        {"id": 4, "name": "Australia", "type": "foreign"},
        {"id": 5, "name": "Japan", "type": "foreign"},
    ],
    "regions": [
        {"id": 1, "name": "CALABARZON"},
        {"id": 2, "name": "NCR"},
        {"id": 3, "name": "Central Luzon"},
        {"id": 4, "name": "Bicol Region"},
    ],
    "provinces": [
        {"id": 1, "name": "Quezon"},
        {"id": 2, "name": "Laguna"},
        {"id": 3, "name": "Batangas"},
        {"id": 4, "name": "Metro Manila"},
        {"id": 5, "name": "Cavite"},
    ],
    "itineraries": [
        {"id": 1, "name": "Island Hopping Circuit"},
        {"id": 2, "name": "Beach and Resort Day Tour"},
        {"id": 3, "name": "Eco Adventure Trail"},
        {"id": 4, "name": "Heritage and Lighthouse Stop"},
    ],
    "travel_modes": [
        {"id": 1, "name": "Private Vehicle"},
        {"id": 2, "name": "Tourist Van"},
        {"id": 3, "name": "Public Bus"},
        {"id": 4, "name": "Ferry / Port Transfer"},
    ],
    "boat_types": [
        {"id": 1, "name": "Motorized Banca"},
        {"id": 2, "name": "Speedboat"},
        {"id": 3, "name": "Passenger Boat"},
    ],
    "visit_purposes": [
        {"id": 1, "name": "Leisure"},
        {"id": 2, "name": "Family Visit"},
        {"id": 3, "name": "Educational Tour"},
        {"id": 4, "name": "Business / Event"},
        {"id": 5, "name": "Pilgrimage / Cultural Visit"},
    ],
    "resorts": [
        {
            "resort_id": 1,
            "resort_name": "Cagbalete Island",
            "with_mayors_permit": True,
            "type": "Island Resort",
            "location": "Barangay Cagbalete I, Mauban, Quezon",
            "short_description": "White-sand island destination known for sandbars, beach camping, and weekend eco escapes.",
            "tourism_rating": 4.8,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "cagbalete",
            "monthly_arrivals": 1860,
            "latitude": 13.9389,
            "longitude": 121.7974,
        },
        {
            "resort_id": 2,
            "resort_name": "Dampalitan Island",
            "with_mayors_permit": True,
            "type": "Island Resort",
            "location": "Barangay Cagbalete II, Mauban, Quezon",
            "short_description": "Popular barkada and family stop with cottage rentals, picnic areas, and calm coastal waters.",
            "tourism_rating": 4.6,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "dampalitan-island",
            "monthly_arrivals": 1495,
            "latitude": 13.9254,
            "longitude": 121.7861,
        },
        {
            "resort_id": 3,
            "resort_name": "Puting Buhangin Cove",
            "with_mayors_permit": False,
            "type": "Beach Resort",
            "location": "Sitio Puting Buhangin, Mauban, Quezon",
            "short_description": "Quiet beach cove with overnight huts, snorkeling areas, and sunrise viewpoints.",
            "tourism_rating": 4.5,
            "access": "Road + Boat",
            "itinerary_ids": [1, 2],
            "image_key": "puting-buhangin",
            "monthly_arrivals": 1160,
            "latitude": 13.9186,
            "longitude": 121.7702,
        },
        {
            "resort_id": 4,
            "resort_name": "Kwebang Lampas",
            "with_mayors_permit": True,
            "type": "Eco Site",
            "location": "Lamon Bay coast, Mauban, Quezon",
            "short_description": "Famous sea cave and beach attraction included in island hopping routes and photo tours.",
            "tourism_rating": 4.7,
            "access": "Boat Access",
            "itinerary_ids": [1, 3],
            "image_key": "kwebang-lampas",
            "monthly_arrivals": 1388,
            "latitude": 13.9247,
            "longitude": 121.7791,
        },
        {
            "resort_id": 5,
            "resort_name": "Mauban Lighthouse",
            "with_mayors_permit": True,
            "type": "Heritage Site",
            "location": "Town Proper, Mauban, Quezon",
            "short_description": "Historic lighthouse stop ideal for educational tours, LGU visits, and cultural orientation.",
            "tourism_rating": 4.3,
            "access": "Road Access",
            "itinerary_ids": [4],
            "image_key": "mauban-lighthouse",
            "monthly_arrivals": 820,
            "latitude": 14.0245,
            "longitude": 121.7317,
        },
        {
            "resort_id": 6,
            "resort_name": "Mt. Pinagbanderahan",
            "with_mayors_permit": True,
            "type": "Eco Adventure",
            "location": "Inland highlands, Mauban, Quezon",
            "short_description": "Mountain trail destination with panoramic ridge views, trekking paths, and camp activity zones.",
            "tourism_rating": 4.4,
            "access": "Road Access",
            "itinerary_ids": [3],
            "image_key": "mt-pinagbanderahan",
            "monthly_arrivals": 680,
            "latitude": 13.9844,
            "longitude": 121.6796,
        },
    ],
}

INITIAL_FEEDBACK_ENTRIES = [
    {
        "id": 1,
        "destination_id": 1,
        "reviewer": "Lara Mendoza",
        "rating": 5,
        "status": "positive",
        "date": "2026-04-10",
        "title": "Very organized island arrival",
        "message": "Boat queue was smooth and the welcome desk gave clear directions for the cottages and sandbar timings.",
    },
    {
        "id": 2,
        "destination_id": 3,
        "reviewer": "Noah Walker",
        "rating": 3,
        "status": "neutral",
        "date": "2026-04-09",
        "title": "Nice beach, limited shaded seating",
        "message": "The location was scenic but more shaded waiting areas near the docking point would help senior guests.",
    },
    {
        "id": 3,
        "destination_id": 4,
        "reviewer": "Mika Tan",
        "rating": 4,
        "status": "positive",
        "date": "2026-04-08",
        "title": "Great guide support",
        "message": "Our guide shared safety reminders before entering the cave, and the experience felt well-managed.",
    },
    {
        "id": 4,
        "destination_id": 2,
        "reviewer": "Joshua Cruz",
        "rating": 2,
        "status": "negative",
        "date": "2026-04-07",
        "title": "Needs cleaner restroom facilities",
        "message": "The island itself was enjoyable, but restroom maintenance needs more frequent attention during peak hours.",
    },
    {
        "id": 5,
        "destination_id": 6,
        "reviewer": "Anne Salazar",
        "rating": 4,
        "status": "positive",
        "date": "2026-04-06",
        "title": "Good eco-trail assistance",
        "message": "Trail markers were visible and staff were helpful in guiding our group through the safer route.",
    },
]

INITIAL_TOURISM_SETTINGS = {
    "municipality_name": "Municipality of Mauban",
    "province": "Quezon",
    "tourism_office_contact": "+63 42 XXX XXXX",
    "tourism_office_email": "tourism@mauban.gov.ph",
    "api_base_url": "https://api.mauban-tourism.gov.ph/v1",
}
