MAUBAN_BARANGAYS = [
    "Abo-abo",
    "Alitap",
    "Baao",
    "Bagong Bayan",
    "Balaybalay",
    "Bato",
    "Cagbalete I",
    "Cagbalete II",
    "Cagsiay I",
    "Cagsiay II",
    "Cagsiay III",
    "Concepcion",
    "Daungan",
    "Liwayway",
    "Lual",
    "Lual Rural",
    "Lucutan",
    "Luya-luya",
    "Mabato",
    "Macasin",
    "Polo",
    "Remedios I",
    "Remedios II",
    "Rizaliana",
    "Rosario",
    "Sadsaran",
    "San Gabriel",
    "San Isidro",
    "San Jose",
    "San Lorenzo",
    "San Miguel",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Lucia",
    "Santo Angel",
    "Santo Niño",
    "Santol",
    "Soledad",
    "Tapucan",
]


INITIAL_TOURIST_RECORDS = [
    {
        "survey_id": "SURV-2026-001",
        "email": "maria.ramos@example.com",
        "full_name": "Maria Teresa Ramos",
        "contact_number": "09171234567",
        "country_id": 1,
        "region_id": 1,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 2,
        "maubanin_count": 1,
        "total_visitors": 3,
        "total_male": 1,
        "total_female": 2,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 3,
        "age_60_above": 0,
        "arrival_date": "2026-04-11",
        "itinerary_id": 1,
        "resort_id": 1,
        "travel_mode_id": 4,
        "boat_type_id": 1,
        "visit_purpose_id": 1,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-002",
        "email": "ethan.lee@example.com",
        "full_name": "Ethan Lee",
        "contact_number": "+63 917 884 2201",
        "country_id": 3,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 2,
        "filipino_count": 1,
        "maubanin_count": 0,
        "total_visitors": 3,
        "total_male": 2,
        "total_female": 1,
        "special_group_count": 1,
        "age_0_7": 0,
        "age_8_59": 3,
        "age_60_above": 0,
        "arrival_date": "2026-04-11",
        "itinerary_id": 1,
        "resort_id": 4,
        "travel_mode_id": 2,
        "boat_type_id": 2,
        "visit_purpose_id": 1,
        "status": "pending",
    },
    {
        "survey_id": "SURV-2026-003",
        "email": "villanueva.family@example.com",
        "full_name": "Jonathan Villanueva",
        "contact_number": "09984561230",
        "country_id": 1,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 0,
        "filipino_count": 4,
        "maubanin_count": 0,
        "total_visitors": 4,
        "total_male": 2,
        "total_female": 2,
        "special_group_count": 2,
        "age_0_7": 1,
        "age_8_59": 3,
        "age_60_above": 0,
        "arrival_date": "2026-04-10",
        "itinerary_id": 2,
        "resort_id": 2,
        "travel_mode_id": 1,
        "boat_type_id": 1,
        "visit_purpose_id": 1,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-004",
        "email": "clare.garcia@example.com",
        "full_name": "Clare Garcia",
        "contact_number": "09170112233",
        "country_id": 1,
        "region_id": 1,
        "province_id": 2,
        "foreigner_count": 0,
        "filipino_count": 2,
        "maubanin_count": 0,
        "total_visitors": 2,
        "total_male": 0,
        "total_female": 2,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 1,
        "age_60_above": 1,
        "arrival_date": "2026-04-09",
        "itinerary_id": 4,
        "resort_id": 5,
        "travel_mode_id": 3,
        "boat_type_id": 3,
        "visit_purpose_id": 3,
        "status": "no_show",
    },
    {
        "survey_id": "SURV-2026-005",
        "email": "akira.tanaka@example.com",
        "full_name": "Akira Tanaka",
        "contact_number": "+63 918 551 9801",
        "country_id": 5,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 1,
        "filipino_count": 1,
        "maubanin_count": 0,
        "total_visitors": 2,
        "total_male": 1,
        "total_female": 1,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 2,
        "age_60_above": 0,
        "arrival_date": "2026-04-08",
        "itinerary_id": 3,
        "resort_id": 6,
        "travel_mode_id": 2,
        "boat_type_id": 3,
        "visit_purpose_id": 3,
        "status": "pending",
    },
    {
        "survey_id": "SURV-2026-006",
        "email": "reyes.team@example.com",
        "full_name": "Camille Reyes",
        "contact_number": "09271114455",
        "country_id": 1,
        "region_id": 1,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 5,
        "maubanin_count": 2,
        "total_visitors": 7,
        "total_male": 4,
        "total_female": 3,
        "special_group_count": 1,
        "age_0_7": 1,
        "age_8_59": 6,
        "age_60_above": 0,
        "arrival_date": "2026-04-07",
        "itinerary_id": 1,
        "resort_id": 1,
        "travel_mode_id": 4,
        "boat_type_id": 1,
        "visit_purpose_id": 4,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-007",
        "email": "daniel.santos@example.com",
        "full_name": "Daniel Santos",
        "contact_number": "09189998877",
        "country_id": 1,
        "region_id": 3,
        "province_id": 5,
        "foreigner_count": 0,
        "filipino_count": 3,
        "maubanin_count": 0,
        "total_visitors": 3,
        "total_male": 2,
        "total_female": 1,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 3,
        "age_60_above": 0,
        "arrival_date": "2026-04-06",
        "itinerary_id": 2,
        "resort_id": 3,
        "travel_mode_id": 1,
        "boat_type_id": 2,
        "visit_purpose_id": 2,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-008",
        "email": "australia.group@example.com",
        "full_name": "Sophie Martin",
        "contact_number": "+63 917 781 9931",
        "country_id": 4,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 4,
        "filipino_count": 1,
        "maubanin_count": 0,
        "total_visitors": 5,
        "total_male": 2,
        "total_female": 3,
        "special_group_count": 1,
        "age_0_7": 0,
        "age_8_59": 5,
        "age_60_above": 0,
        "arrival_date": "2026-04-05",
        "itinerary_id": 1,
        "resort_id": 2,
        "travel_mode_id": 2,
        "boat_type_id": 2,
        "visit_purpose_id": 1,
        "status": "pending",
    },
    {
        "survey_id": "SURV-2026-009",
        "email": "local.hikers@example.com",
        "full_name": "Arvin Mendoza",
        "contact_number": "09081239876",
        "country_id": 1,
        "region_id": 1,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 2,
        "maubanin_count": 3,
        "total_visitors": 5,
        "total_male": 3,
        "total_female": 2,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 4,
        "age_60_above": 1,
        "arrival_date": "2026-04-04",
        "itinerary_id": 3,
        "resort_id": 6,
        "travel_mode_id": 1,
        "boat_type_id": 3,
        "visit_purpose_id": 1,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-010",
        "email": "school.trip@example.com",
        "full_name": "Helen de la Cruz",
        "contact_number": "09195550066",
        "country_id": 1,
        "region_id": 4,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 18,
        "maubanin_count": 0,
        "total_visitors": 18,
        "total_male": 8,
        "total_female": 10,
        "special_group_count": 3,
        "age_0_7": 0,
        "age_8_59": 18,
        "age_60_above": 0,
        "arrival_date": "2026-04-03",
        "itinerary_id": 4,
        "resort_id": 5,
        "travel_mode_id": 3,
        "boat_type_id": 3,
        "visit_purpose_id": 3,
        "status": "arrived",
    },
    {
        "survey_id": "SURV-2026-011",
        "email": "weekend.barkada@example.com",
        "full_name": "Paolo Navarro",
        "contact_number": "09183334455",
        "country_id": 1,
        "region_id": 2,
        "province_id": 4,
        "foreigner_count": 0,
        "filipino_count": 6,
        "maubanin_count": 0,
        "total_visitors": 6,
        "total_male": 3,
        "total_female": 3,
        "special_group_count": 0,
        "age_0_7": 0,
        "age_8_59": 6,
        "age_60_above": 0,
        "arrival_date": "2026-04-02",
        "itinerary_id": 2,
        "resort_id": 3,
        "travel_mode_id": 1,
        "boat_type_id": 1,
        "visit_purpose_id": 1,
        "status": "pending",
    },
    {
        "survey_id": "SURV-2026-012",
        "email": "mauban.office@example.com",
        "full_name": "Rina Castillo",
        "contact_number": "09171116677",
        "country_id": 1,
        "region_id": 1,
        "province_id": 1,
        "foreigner_count": 0,
        "filipino_count": 2,
        "maubanin_count": 4,
        "total_visitors": 6,
        "total_male": 2,
        "total_female": 4,
        "special_group_count": 1,
        "age_0_7": 1,
        "age_8_59": 4,
        "age_60_above": 1,
        "arrival_date": "2026-04-01",
        "itinerary_id": 4,
        "resort_id": 5,
        "travel_mode_id": 1,
        "boat_type_id": 3,
        "visit_purpose_id": 5,
        "status": "arrived",
    },
]

REFERENCE_TABLES = {
    "countries": [
        {"id": 1, "name": "Philippines", "type": "local"},
        {"id": 2, "name": "United States", "type": "foreign"},
        {"id": 3, "name": "South Korea", "type": "foreign"},
        {"id": 4, "name": "Australia", "type": "foreign"},
        {"id": 5, "name": "Japan", "type": "foreign"},
        {"id": 6, "name": "International", "type": "foreign"},
    ],
    "regions": [
        {"id": 1, "name": "Region I - Ilocos Region", "code": "01"},
        {"id": 2, "name": "Region II - Cagayan Valley", "code": "02"},
        {"id": 3, "name": "Region III - Central Luzon", "code": "03"},
        {"id": 4, "name": "CALABARZON Region", "code": "04"},
        {"id": 5, "name": "MIMAROPA Region", "code": "17"},
        {"id": 6, "name": "Region V - Bicol Region", "code": "05"},
        {"id": 7, "name": "NCR - National Capital Region", "code": "13"},
        {"id": 8, "name": "CAR - Cordillera Administrative Region", "code": "14"},
        {"id": 9, "name": "Region VI - Western Visayas", "code": "06"},
        {"id": 10, "name": "Region VII - Central Visayas", "code": "07"},
        {"id": 11, "name": "Region VIII - Eastern Visayas", "code": "08"},
        {"id": 12, "name": "Region IX - Zamboanga Peninsula", "code": "09"},
        {"id": 13, "name": "Region X - Northern Mindanao", "code": "10"},
        {"id": 14, "name": "Region XI - Davao Region", "code": "11"},
        {"id": 15, "name": "Region XII - SOCCSKSARGEN", "code": "12"},
        {"id": 16, "name": "Region XIII - Caraga", "code": "16"},
        {"id": 17, "name": "Autonomous Region in Muslim Mindanao (ARMM)", "code": "15"},
    ],
    "provinces": [
        {"id": 1, "name": "Quezon"},
        {"id": 2, "name": "Laguna"},
        {"id": 3, "name": "Batangas"},
        {"id": 4, "name": "Metro Manila"},
        {"id": 5, "name": "Cavite"},
    ],
    "itineraries": [
        {"id": 1, "name": "Overnight"},
        {"id": 2, "name": "Day Tour"},
        {"id": 3, "name": "2 Nights"},
        {"id": 4, "name": "3 Nights"},
        {"id": 5, "name": "4 Nights"},
        {"id": 6, "name": "5 Nights and above"},
    ],
    "travel_modes": [
        {"id": 1, "name": "Private Vehicle"},
        {"id": 2, "name": "Public Utility Vehicle"},
        {"id": 3, "name": "Public Bus"},
        {"id": 4, "name": "Ferry / Port Transfer"},
    ],
    "boat_types": [
        {"id": 1, "name": "Public Boat (P100/ride/head) Sabang Port Only"},
        {"id": 2, "name": "Private Boat (Rates depend on the capacity)"},
        {"id": 3, "name": "Boat Provided by Resort (As confirmed by both guests and resort)"},
    ],
    "visit_purposes": [
        {"id": 1, "name": "Leisure"},
        {"id": 2, "name": "Vacation"},
        {"id": 3, "name": "Business"},
        {"id": 4, "name": "Visit"},
        {"id": 5, "name": "Outing"},
        {"id": 6, "name": "Tour"},
        {"id": 7, "name": "Team Building"},
        {"id": 8, "name": "Travel"},
        {"id": 9, "name": "Swimming"},
        {"id": 10, "name": "Unwind"},
    ],
    "resorts": [
        {
            "resort_id": 1,
            "resort_name": "Dona Choleng Camping Resort",
            "with_mayors_permit": True,
            "type": "Camping Resort",
            "location": "Cagbalete",
            "short_description": "Cagbalete camping resort for overnight stays, group visits, and beachside recreation.",
            "tourism_rating": 4.8,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "dona-choleng-camping-resort",
            "monthly_arrivals": 1842,
            "latitude": 14.2748,
            "longitude": 121.8239,
        },
        {
            "resort_id": 2,
            "resort_name": "Aquazul Hotel and Resort",
            "with_mayors_permit": True,
            "type": "Hotel and Resort",
            "location": "Cagbalete",
            "short_description": "Island hotel and resort destination serving families, tour groups, and overnight visitors.",
            "tourism_rating": 4.7,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "aquazul-hotel-and-resort",
            "monthly_arrivals": 1456,
            "latitude": 14.2716,
            "longitude": 121.8264,
        },
        {
            "resort_id": 3,
            "resort_name": "Rio Del Sol Beach Resort",
            "with_mayors_permit": True,
            "type": "Beach Resort",
            "location": "Cagbalete",
            "short_description": "Beach resort known for open shoreline views, day tours, and relaxing seaside stays.",
            "tourism_rating": 4.6,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "rio-del-sol-beach-resort",
            "monthly_arrivals": 982,
            "latitude": 14.2682,
            "longitude": 121.8291,
        },
        {
            "resort_id": 4,
            "resort_name": "Jovencio's Resort",
            "with_mayors_permit": True,
            "type": "Beach Resort",
            "location": "Cagbalete",
            "short_description": "Cagbalete beach resort for small groups, casual swimming, and island leisure trips.",
            "tourism_rating": 4.3,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "jovencios-resort",
            "monthly_arrivals": 648,
            "latitude": 14.2655,
            "longitude": 121.8218,
        },
        {
            "resort_id": 5,
            "resort_name": "MVT Sto. Nino Beach Resort",
            "with_mayors_permit": True,
            "type": "Beach Resort",
            "location": "Cagbalete",
            "short_description": "Beach resort destination with shaded shoreline areas and family-friendly island access.",
            "tourism_rating": 4.4,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "mvt-sto-nino-beach-resort",
            "monthly_arrivals": 512,
            "latitude": 14.2631,
            "longitude": 121.8245,
        },
        {
            "resort_id": 6,
            "resort_name": "Nilandingan Cove Resort",
            "with_mayors_permit": True,
            "type": "Cove Resort",
            "location": "Cagbalete",
            "short_description": "Cove resort destination for beach relaxation, coastal scenery, and low-density stays.",
            "tourism_rating": 4.3,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "nilandingan-cove-resort",
            "monthly_arrivals": 384,
            "latitude": 14.2604,
            "longitude": 121.8278,
        },
        {
            "resort_id": 7,
            "resort_name": "Villa Cleofas Cagbalete",
            "with_mayors_permit": True,
            "type": "Camping Resort",
            "location": "Cagbalete",
            "short_description": "Popular Cagbalete camping resort for overnight beach stays and group activities.",
            "tourism_rating": 4.8,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "villa-cleofas-cagbalete",
            "monthly_arrivals": 1842,
            "latitude": 14.2577,
            "longitude": 121.8212,
        },
        {
            "resort_id": 8,
            "resort_name": "Villa Escaparde Camping and Beach Resort",
            "with_mayors_permit": True,
            "type": "Camping and Beach Resort",
            "location": "Cagbalete",
            "short_description": "Camping and beach resort serving barkada trips, family stays, and island recreation.",
            "tourism_rating": 4.7,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "villa-escaparde-camping-and-beach-resort",
            "monthly_arrivals": 1456,
            "latitude": 14.2552,
            "longitude": 121.8251,
        },
        {
            "resort_id": 9,
            "resort_name": "Villa Noe Beach",
            "with_mayors_permit": True,
            "type": "Beach Resort",
            "location": "Cagbalete",
            "short_description": "Beach resort destination offering seaside cottages, island scenery, and visitor accommodations.",
            "tourism_rating": 4.6,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "villa-noe-beach",
            "monthly_arrivals": 982,
            "latitude": 14.2529,
            "longitude": 121.8287,
        },
        {
            "resort_id": 10,
            "resort_name": "Villa Pilarosa Beach Resort",
            "with_mayors_permit": True,
            "type": "Beach Resort",
            "location": "Cagbalete",
            "short_description": "Beach resort for swimming, cottage stays, and relaxed Cagbalete shoreline visits.",
            "tourism_rating": 4.3,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "villa-pilarosa-beach-resort",
            "monthly_arrivals": 648,
            "latitude": 14.2507,
            "longitude": 121.8229,
        },
        {
            "resort_id": 11,
            "resort_name": "Tita Pinay Beach Resort",
            "with_mayors_permit": True,
            "type": "Beach Resort",
            "location": "Cagbalete",
            "short_description": "Beach resort for family trips, day tours, and simple island lodging.",
            "tourism_rating": 4.4,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "tita-pinay-beach-resort",
            "monthly_arrivals": 512,
            "latitude": 14.2484,
            "longitude": 121.8261,
        },
        {
            "resort_id": 12,
            "resort_name": "Aguho Playa Beach Resort",
            "with_mayors_permit": False,
            "type": "Beach Resort",
            "location": "Cagbalete",
            "short_description": "Beach resort listed for tourism monitoring and permit follow-up.",
            "tourism_rating": 4.3,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "aguho-playa-beach-resort",
            "monthly_arrivals": 384,
            "latitude": 14.2462,
            "longitude": 121.8296,
        },
        {
            "resort_id": 13,
            "resort_name": "Tent Place",
            "with_mayors_permit": True,
            "type": "Camping Resort",
            "location": "Cagbalete",
            "short_description": "Camping destination for tent stays, island leisure, and beach group activities.",
            "tourism_rating": 4.8,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "tent-place",
            "monthly_arrivals": 1842,
            "latitude": 14.2438,
            "longitude": 121.8235,
        },
        {
            "resort_id": 14,
            "resort_name": "Orlan Beach Resort",
            "with_mayors_permit": True,
            "type": "Beach Resort",
            "location": "Cagbalete",
            "short_description": "Beach resort for island visitors, coastal recreation, and overnight stays.",
            "tourism_rating": 4.8,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "orlan-beach-resort",
            "monthly_arrivals": 1842,
            "latitude": 14.2416,
            "longitude": 121.8272,
        },
        {
            "resort_id": 15,
            "resort_name": "Nenita Del Sol",
            "with_mayors_permit": True,
            "type": "Beach Resort",
            "location": "Cagbalete",
            "short_description": "Beach destination monitored for tourist arrivals, guest stays, and permit compliance.",
            "tourism_rating": 4.8,
            "access": "Boat Access",
            "itinerary_ids": [1, 2],
            "image_key": "nenita-del-sol",
            "monthly_arrivals": 1842,
            "latitude": 14.2393,
            "longitude": 121.8301,
        },
    ],
}

INITIAL_FEEDBACK_ENTRIES = [
    {
        "id": 1,
        "destination_id": 1,
        "reviewer": "Lara Mendoza",
        "rating": 5,
        "status": "positive",
        "date": "2026-04-10",
        "title": "Very organized island arrival",
        "message": "Boat queue was smooth and Dona Choleng staff gave clear directions for cottages and camp areas.",
    },
    {
        "id": 2,
        "destination_id": 3,
        "reviewer": "Noah Walker",
        "rating": 3,
        "status": "neutral",
        "date": "2026-04-09",
        "title": "Nice beach, limited shaded seating",
        "message": "Rio Del Sol was scenic but more shaded waiting areas near the docking point would help senior guests.",
    },
    {
        "id": 3,
        "destination_id": 4,
        "reviewer": "Mika Tan",
        "rating": 4,
        "status": "positive",
        "date": "2026-04-08",
        "title": "Great guide support",
        "message": "Jovencio's Resort staff shared clear safety reminders and the beach activity felt well-managed.",
    },
    {
        "id": 4,
        "destination_id": 2,
        "reviewer": "Joshua Cruz",
        "rating": 2,
        "status": "negative",
        "date": "2026-04-07",
        "title": "Needs cleaner restroom facilities",
        "message": "Aquazul was enjoyable, but restroom maintenance needs more frequent attention during peak hours.",
    },
    {
        "id": 5,
        "destination_id": 6,
        "reviewer": "Anne Salazar",
        "rating": 4,
        "status": "positive",
        "date": "2026-04-06",
        "title": "Good eco-trail assistance",
        "message": "MVT Sto. Nino staff were helpful in guiding our group through the safer beach access route.",
    },
]

# ============================================================
# SANITATION MODULE SEED DATA
# Business / Permit Side
# ============================================================

STANDARD_SANITARY_REQUIREMENTS = [
    "Xerox copy of DTI/SEC/CDA",
    "Barangay Clearance of owner",
    "Chest X-ray Results (Owner & employees)",
    "CTC/Cedula of owner and employees",
    "1x1 picture of owner and employees",
    "Potability of Water Supply - Physical/Chemical Examination",
    "Potability of Water Supply - Microbiological Examination",
]

ADDITIONAL_SANITARY_REQUIREMENTS_BY_TYPE = {
    "Water Refilling Station": [
        "Certificate of Potability of Product Water",
        "DOH Operational Permit Certificate",
        "Certificate of 40-hour Training Course (Owner)",
        "Water Safety Plan",
        "NWRB Water Permit Certificate",
    ],
    "Agro-industrial Establishment (Poultry / Piggery Farm)": [
        "DENR-EMB ECC or CNC",
        "Waste Water Treatment Facility",
    ],
    "Restaurant / Food Establishment": [
        "Stool Examination result (for food establishments only)",
    ],
    "Public Market Stall": [
        "Stool Examination result (for food establishments only)",
    ],
    "Drug Store": [
        "DOH License to Operate",
        "PRC License of Pharmacist",
    ],
    "Sub-contractor": [
        "Physical Examination of all Employees",
        "Scope of Work",
        "Full-time First Aider (1-60 employees)",
        "Full-time First Aider and Part-Time OH Nurse (61-99 employees)",
        "Part-Time OH Physician and Dentist, Full-time OH Nurse, and First Aider (100-199 employees)",
        "Part-Time OH Physician and Dentist, Full-time OH Nurse, and First Aider (200-600 employees)",
        "Full-time OH Physician and Dentist, Full-time OH Nurse, and First Aider (601-2000 employees)",
    ],
    "Resort / Picnic Ground": [
        "Trained Lifeguard",
        "Life Saving Equipment",
        "First Aid Kit",
        "Waste Water Treatment Facility",
    ],
    "Boatman": [
        "Life Vest",
        "MARINA Certificate of License of Boatman",
        "First Aid Kit",
    ],
    "Massage / Physical Therapy": [
        "License of Physical Therapist",
        "NC2 Certification of Massage Therapist",
        "Hepa B Screening",
    ],
    "Funeral Parlor": [
        "License of Embalmer",
        "DOH License to Operate Certificate",
    ],
    "Burial Ground": [
        "Operational Clearance from DOH Regional Office",
    ],
    "Private Laboratory & Clinic": [
        "DOH License to Operate Certificate",
        "PRC License of MedTech/RadTech/Nurse/Doctor",
        "Hepa B Screening or anti Hepa B Vaccination",
        "Special Waste Facility and MOA with Service Provider",
    ],
    "Karaoke / Video Bar / CSW": [
        "Hepa B Screening",
        "Regular Smear",
        "NSO Birth Certificate",
    ],
}

SP_ADDITIONAL_SANITARY_REQUIREMENTS_BY_TYPE = {
    "Water Refilling Station": [
        "Certificate of Potability of Product Water",
        "DOH Operational Permit Certificate",
        "Certificate of 40-hour Training Course (Owner)",
    ],
    "Agro-industrial Establishment (Poultry / Piggery Farm)": [
        "DENR-EMB ECC or CNC",
    ],
    "Restaurant / Food Establishment": [
        "Stool Examination result (for food establishments only)",
    ],
    "Public Market Stall": [
        "Stool Examination result (for food establishments only)",
    ],
    "Drug Store": [
        "DOH License to Operate",
    ],
    "Sub-contractor": [
        "Physical Examination of all Employees",
        "Scope of Work",
        "Full-time First Aider (1-60 employees)",
    ],
    "Resort / Picnic Ground": [
        "Trained Lifeguard",
        "First Aid Kit",
    ],
    "Boatman": [
        "Life Vest",
        "MARINA Certificate of License of Boatman",
    ],
    "Massage / Physical Therapy": [
        "License of Physical Therapist",
        "NC2 Certification of Massage Therapist",
        "Hepa B Screening",
    ],
    "Funeral Parlor": [
        "License of Embalmer",
    ],
    "Burial Ground": [
        "Operational Clearance from DOH Regional Office",
    ],
    "Private Laboratory & Clinic": [
        "DOH License to Operate Certificate",
        "PRC License of MedTech/RadTech/Nurse/Doctor",
    ],
    "Karaoke / Video Bar / CSW": [
        "Hepa B Screening",
        "Regular Smear",
    ],
}

LEGACY_SANITARY_BUSINESS_TYPE_ALIASES = {
    "Poultry Farm": "Agro-industrial Establishment (Poultry / Piggery Farm)",
    "Restaurant / Food Service": "Restaurant / Food Establishment",
    "Barbershop / Salon": "Massage / Physical Therapy",
    "Gasoline Station": "Sub-contractor",
    "Motorshop": "Sub-contractor",
}

SANITARY_BUSINESS_TYPES = [
    {
        "name": "Water Refilling Station",
        "inspection_frequency": "monthly",
        "description": "Water-related establishment requiring regular potability and sanitation monitoring.",
    },
    {
        "name": "Agro-industrial Establishment (Poultry / Piggery Farm)",
        "inspection_frequency": "quarterly",
        "description": "Agro-industrial poultry or piggery establishment monitored for wastewater, environmental clearance, and sanitation compliance.",
    },
    {
        "name": "Restaurant / Food Establishment",
        "inspection_frequency": "monthly",
        "description": "Food establishment requiring sanitary, potability, and employee health requirement monitoring.",
    },
    {
        "name": "Public Market Stall",
        "inspection_frequency": "monthly",
        "description": "Market stall monitored for food-handling, employee health, potability, and sanitary permit requirements.",
    },
    {
        "name": "Drug Store",
        "inspection_frequency": "annual",
        "description": "Drug store monitored for DOH operating authority and pharmacist licensing requirements.",
    },
    {
        "name": "Sub-contractor",
        "inspection_frequency": "annual",
        "description": "Contracted service establishment monitored for employee health and occupational health staffing requirements.",
    },
    {
        "name": "Resort / Picnic Ground",
        "inspection_frequency": "quarterly",
        "description": "Recreational establishment monitored for lifeguard, first aid, safety equipment, and wastewater requirements.",
    },
    {
        "name": "Boatman",
        "inspection_frequency": "annual",
        "description": "Boat operation service monitored for life vest, MARINA license, and first aid readiness.",
    },
    {
        "name": "Massage / Physical Therapy",
        "inspection_frequency": "quarterly",
        "description": "Therapy service establishment monitored for professional license, NC2 certification, and Hepa B screening.",
    },
    {
        "name": "Funeral Parlor",
        "inspection_frequency": "annual",
        "description": "Funeral service establishment monitored for embalmer license and DOH operating certificate.",
    },
    {
        "name": "Burial Ground",
        "inspection_frequency": "annual",
        "description": "Burial ground monitored for DOH regional operational clearance.",
    },
    {
        "name": "Private Laboratory & Clinic",
        "inspection_frequency": "annual",
        "description": "Health service establishment monitored for DOH license, professional licenses, vaccination or screening, and special waste agreement.",
    },
    {
        "name": "Karaoke / Video Bar / CSW",
        "inspection_frequency": "monthly",
        "description": "Entertainment or CSW-related establishment monitored for Hepa B screening, regular smear, and birth certificate requirements.",
    },
]

SANITARY_REQUIREMENTS = [
    {
        "business_type": business_type["name"],
        "permit_size": permit_size,
        "requirements": STANDARD_SANITARY_REQUIREMENTS
        + (
            SP_ADDITIONAL_SANITARY_REQUIREMENTS_BY_TYPE
            if permit_size == "sp"
            else ADDITIONAL_SANITARY_REQUIREMENTS_BY_TYPE
        ).get(business_type["name"], []),
    }
    for business_type in SANITARY_BUSINESS_TYPES
    for permit_size in ("sp", "large")
]

SANITARY_ESTABLISHMENTS = [
    {
        "business_name": "AquaPure Refilling",
        "owner_name": "Maria Santos",
        "business_type": "Water Refilling Station",
        "permit_size": "sp",
        "barangay": "San Isidro",
        "address": "Brgy. San Isidro, Mauban, Quezon",
        "contact_number": "09170000001",
        "has_permit": True,
        "permit_number": "SP-2026-001",
        "permit_issued_date": "2026-01-10",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "good_standing",
        "permit_status": "active",
        "latitude": 14.1878,
        "longitude": 121.7254,
        "remarks": "Compliant during latest inspection.",
    },
    {
        "business_name": "Golden Egg Poultry",
        "owner_name": "Jose Ramirez",
        "business_type": "Agro-industrial Establishment (Poultry / Piggery Farm)",
        "permit_size": "large",
        "barangay": "Malabanan",
        "address": "Brgy. Malabanan, Mauban, Quezon",
        "contact_number": "09170000002",
        "has_permit": True,
        "permit_number": "LG-2026-002",
        "permit_issued_date": "2026-01-15",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "violation",
        "permit_status": "suspended",
        "latitude": 14.1788,
        "longitude": 121.7332,
        "remarks": "Requires immediate enforcement attention.",
    },
    {
        "business_name": "Petron Highway",
        "owner_name": "PMC Corp.",
        "business_type": "Sub-contractor",
        "permit_size": "large",
        "barangay": "Poblacion",
        "address": "Brgy. Poblacion, Mauban, Quezon",
        "contact_number": "09170000003",
        "has_permit": True,
        "permit_number": "LG-2026-003",
        "permit_issued_date": "2026-02-05",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "good_standing",
        "permit_status": "active",
        "latitude": 14.1852,
        "longitude": 121.7305,
        "remarks": "Good standing.",
    },
    {
        "business_name": "Lola Nena’s Eatery",
        "owner_name": "Helena Cruz",
        "business_type": "Restaurant / Food Establishment",
        "permit_size": "sp",
        "barangay": "Poblacion",
        "address": "Brgy. Poblacion, Mauban, Quezon",
        "contact_number": "09170000004",
        "has_permit": True,
        "permit_number": "SP-2026-004",
        "permit_issued_date": "2026-02-18",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "upcoming",
        "permit_status": "renewal_due",
        "latitude": 14.1841,
        "longitude": 121.7282,
        "remarks": "Inspection due within monitoring period.",
    },
    {
        "business_name": "Sunrise Bistro",
        "owner_name": "Carlos Tan",
        "business_type": "Restaurant / Food Establishment",
        "permit_size": "large",
        "barangay": "San Roque",
        "address": "Brgy. San Roque, Mauban, Quezon",
        "contact_number": "09170000005",
        "has_permit": True,
        "permit_number": "LG-2026-005",
        "permit_issued_date": "2026-03-02",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "for_completion",
        "permit_status": "conditional",
        "latitude": 14.1904,
        "longitude": 121.7249,
        "remarks": "Pending completion of requirements.",
    },
    {
        "business_name": "Style Cuts Salon",
        "owner_name": "Anne Reyes",
        "business_type": "Massage / Physical Therapy",
        "permit_size": "sp",
        "barangay": "Bagong Pook",
        "address": "Brgy. Bagong Pook, Mauban, Quezon",
        "contact_number": "09170000006",
        "has_permit": True,
        "permit_number": "SP-2026-006",
        "permit_issued_date": "2026-02-15",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "good_standing",
        "permit_status": "active",
        "latitude": 14.1822,
        "longitude": 121.7364,
        "remarks": "Good standing.",
    },
    {
        "business_name": "Crystal Springs Water",
        "owner_name": "B. Aquino",
        "business_type": "Water Refilling Station",
        "permit_size": "large",
        "barangay": "San Isidro",
        "address": "Brgy. San Isidro, Mauban, Quezon",
        "contact_number": "09170000007",
        "has_permit": True,
        "permit_number": "LG-2026-007",
        "permit_issued_date": "2026-03-22",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "good_standing",
        "permit_status": "active",
        "latitude": 14.1899,
        "longitude": 121.7374,
        "remarks": "Good standing.",
    },
    {
        "business_name": "Shell Junction",
        "owner_name": "Shell Phils.",
        "business_type": "Sub-contractor",
        "permit_size": "large",
        "barangay": "Poblacion",
        "address": "Brgy. Poblacion, Mauban, Quezon",
        "contact_number": "09170000008",
        "has_permit": True,
        "permit_number": "LG-2026-008",
        "permit_issued_date": "2026-01-30",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "upcoming",
        "permit_status": "renewal_due",
        "latitude": 14.1867,
        "longitude": 121.7315,
        "remarks": "Renewal and inspection due soon.",
    },
    {
        "business_name": "Happy Hen Farm",
        "owner_name": "R. Delgado",
        "business_type": "Agro-industrial Establishment (Poultry / Piggery Farm)",
        "permit_size": "sp",
        "barangay": "Malabanan",
        "address": "Brgy. Malabanan, Mauban, Quezon",
        "contact_number": "09170000009",
        "has_permit": True,
        "permit_number": "SP-2026-009",
        "permit_issued_date": "2026-02-10",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "for_completion",
        "permit_status": "conditional",
        "latitude": 14.1769,
        "longitude": 121.7298,
        "remarks": "Pending requirement completion.",
    },
    {
        "business_name": "Market Stall #14",
        "owner_name": "L. Mendoza",
        "business_type": "Public Market Stall",
        "permit_size": "sp",
        "barangay": "Poblacion",
        "address": "Public Market, Brgy. Poblacion, Mauban, Quezon",
        "contact_number": "09170000010",
        "has_permit": True,
        "permit_number": "SP-2026-010",
        "permit_issued_date": "2026-02-28",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "violation",
        "permit_status": "suspended",
        "latitude": 14.1832,
        "longitude": 121.7294,
        "remarks": "Violation recorded during inspection.",
    },
    {
        "business_name": "Manong Pedro’s Carinderia",
        "owner_name": "P. Villanueva",
        "business_type": "Restaurant / Food Establishment",
        "permit_size": "sp",
        "barangay": "San Roque",
        "address": "Brgy. San Roque, Mauban, Quezon",
        "contact_number": "09170000011",
        "has_permit": True,
        "permit_number": "SP-2026-011",
        "permit_issued_date": "2026-03-25",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "good_standing",
        "permit_status": "active",
        "latitude": 14.1918,
        "longitude": 121.7268,
        "remarks": "Good standing.",
    },
    {
        "business_name": "FreshCut Barber",
        "owner_name": "M. Bautista",
        "business_type": "Massage / Physical Therapy",
        "permit_size": "sp",
        "barangay": "Bagong Pook",
        "address": "Brgy. Bagong Pook, Mauban, Quezon",
        "contact_number": "09170000012",
        "has_permit": True,
        "permit_number": "SP-2026-012",
        "permit_issued_date": "2026-02-22",
        "permit_expiry_date": "2026-12-31",
        "compliance_status": "good_standing",
        "permit_status": "active",
        "latitude": 14.1814,
        "longitude": 121.7388,
        "remarks": "Good standing.",
    },
    {
        "business_name": "IOT MOTO",
        "owner_name": "Nerjie Mecantina",
        "business_type": "Sub-contractor",
        "permit_size": "sp",
        "barangay": "Polo",
        "address": "Brgy. Polo, Mauban, Quezon",
        "contact_number": "09170000013",
        "has_permit": False,
        "permit_number": "",
        "permit_issued_date": None,
        "permit_expiry_date": None,
        "compliance_status": "no_permit",
        "permit_status": "no_permit",
        "latitude": 14.1748,
        "longitude": 121.7412,
        "remarks": "No sanitary permit recorded.",
    },
]

SANITARY_INSPECTIONS = [
    {
        "business_name": "AquaPure Refilling",
        "inspector_name": "Insp. J. Cruz",
        "inspection_date": "2026-03-12",
        "next_due_date": "2026-04-12",
        "status_after_inspection": "good_standing",
        "findings": "Requirements complied with during inspection.",
        "remarks": "Continue regular monthly monitoring.",
        "is_draft": False,
        "checklist": [
            {"requirement_name": "Xerox copy of DTI/SEC/CDA", "is_complied": True},
            {"requirement_name": "Barangay Clearance of owner", "is_complied": True},
            {"requirement_name": "Potability of Water Supply - Microbiological Examination", "is_complied": True},
            {"requirement_name": "Certificate of Potability of Product Water", "is_complied": True},
            {"requirement_name": "DOH Operational Permit Certificate", "is_complied": True},
        ],
    },
    {
        "business_name": "Golden Egg Poultry",
        "inspector_name": "Insp. J. Cruz",
        "inspection_date": "2026-01-20",
        "next_due_date": "2026-04-20",
        "status_after_inspection": "violation",
        "findings": "Waste handling and vector control concerns were observed.",
        "remarks": "Requires immediate corrective action.",
        "is_draft": False,
        "checklist": [
            {"requirement_name": "Xerox copy of DTI/SEC/CDA", "is_complied": True},
            {"requirement_name": "Chest X-ray Results (Owner & employees)", "is_complied": True},
            {"requirement_name": "DENR-EMB ECC or CNC", "is_complied": False},
            {"requirement_name": "Waste Water Treatment Facility", "is_complied": False},
        ],
    },
    {
        "business_name": "Sunrise Bistro",
        "inspector_name": "Insp. M. Santos",
        "inspection_date": "2026-03-02",
        "next_due_date": "2026-04-02",
        "status_after_inspection": "for_completion",
        "findings": "Some food safety documents are pending submission.",
        "remarks": "For completion within the required compliance period.",
        "is_draft": False,
        "checklist": [
            {"requirement_name": "Barangay Clearance of owner", "is_complied": True},
            {"requirement_name": "Chest X-ray Results (Owner & employees)", "is_complied": True},
            {"requirement_name": "CTC/Cedula of owner and employees", "is_complied": False},
            {"requirement_name": "Stool Examination result (for food establishments only)", "is_complied": False},
        ],
    },
    {
        "business_name": "Market Stall #14",
        "inspector_name": "Insp. M. Santos",
        "inspection_date": "2026-02-28",
        "next_due_date": "2026-03-28",
        "status_after_inspection": "violation",
        "findings": "Cleaning log and sanitation compliance were not properly maintained.",
        "remarks": "Subject for follow-up inspection.",
        "is_draft": False,
        "checklist": [
            {"requirement_name": "Xerox copy of DTI/SEC/CDA", "is_complied": True},
            {"requirement_name": "1x1 picture of owner and employees", "is_complied": False},
            {"requirement_name": "Stool Examination result (for food establishments only)", "is_complied": False},
        ],
    },
]

# ============================================================
# HOUSEHOLD SANITATION SEED DATA
# ============================================================

HOUSEHOLD_SANITATION_RECORDS = [
    {
        "household_code": "H-0001",
        "household_head": "Dela Cruz, Coedy",
        "barangay": "Poblacion",
        "address": "Brgy. Poblacion, Mauban, Quezon",
        "male_count": 1,
        "female_count": 1,
        "toilet_type": "water_sealed",
        "water_level": "level_3",
        "water_source": "LGU Waterworks",
        "waste_disposal": "collected",
        "status": "good_standing",
        "latitude": 14.1852,
        "longitude": 121.7285,
        "remarks": "Compliant household sanitation profile.",
        "last_survey_date": "2026-04-01",
    },
    {
        "household_code": "H-0002",
        "household_head": "Santos, Juan",
        "barangay": "Poblacion",
        "address": "Brgy. Poblacion, Mauban, Quezon",
        "male_count": 4,
        "female_count": 3,
        "toilet_type": "pour_flush",
        "water_level": "level_1",
        "water_source": "Deep Well",
        "waste_disposal": "composted",
        "status": "violation",
        "latitude": 14.1884,
        "longitude": 121.7318,
        "remarks": "Requires follow-up due to sanitation risk indicators.",
        "last_survey_date": "2026-04-01",
    },
    {
        "household_code": "H-0003",
        "household_head": "Trish-Anne Huidem",
        "barangay": "San Isidro",
        "address": "Brgy. San Isidro, Mauban, Quezon",
        "male_count": 1,
        "female_count": 2,
        "toilet_type": "pit_latrine",
        "water_level": "level_2",
        "water_source": "Communal Faucet",
        "waste_disposal": "burned",
        "status": "for_completion",
        "latitude": 14.1816,
        "longitude": 121.7359,
        "remarks": "For completion of sanitation improvement.",
        "last_survey_date": "2026-04-02",
    },
    {
        "household_code": "H-0004",
        "household_head": "Julia Santos",
        "barangay": "San Roque",
        "address": "Brgy. San Roque, Mauban, Quezon",
        "male_count": 2,
        "female_count": 1,
        "toilet_type": "none",
        "water_level": "level_3",
        "water_source": "LGU Waterworks",
        "waste_disposal": "dumped",
        "status": "violation",
        "latitude": 14.1921,
        "longitude": 121.7247,
        "remarks": "No toilet facility recorded.",
        "last_survey_date": "2026-04-02",
    },
    {
        "household_code": "H-0005",
        "household_head": "Beca Mitchel",
        "barangay": "Malabanan",
        "address": "Brgy. Malabanan, Mauban, Quezon",
        "male_count": 4,
        "female_count": 4,
        "toilet_type": "water_sealed",
        "water_level": "level_1",
        "water_source": "LGU Waterworks",
        "waste_disposal": "collected",
        "status": "good_standing",
        "latitude": 14.1779,
        "longitude": 121.7298,
        "remarks": "Good standing.",
        "last_survey_date": "2026-04-03",
    },
    {
        "household_code": "H-0006",
        "household_head": "Dela Cruz, Juan",
        "barangay": "Malabanan",
        "address": "Brgy. Malabanan, Mauban, Quezon",
        "male_count": 3,
        "female_count": 3,
        "toilet_type": "pour_flush",
        "water_level": "level_2",
        "water_source": "Communal Faucet",
        "waste_disposal": "composted",
        "status": "good_standing",
        "latitude": 14.1897,
        "longitude": 121.7384,
        "remarks": "Good standing.",
        "last_survey_date": "2026-04-03",
    },
    {
        "household_code": "H-0007",
        "household_head": "Nerjie Mecantina",
        "barangay": "San Isidro",
        "address": "Brgy. San Isidro, Mauban, Quezon",
        "male_count": 2,
        "female_count": 2,
        "toilet_type": "pit_latrine",
        "water_level": "level_3",
        "water_source": "LGU Waterworks",
        "waste_disposal": "burned",
        "status": "good_standing",
        "latitude": 14.1745,
        "longitude": 121.7336,
        "remarks": "Good standing.",
        "last_survey_date": "2026-04-04",
    },
    {
        "household_code": "H-0008",
        "household_head": "Wennielyn Lorenzana",
        "barangay": "Bagong Pook",
        "address": "Brgy. Bagong Pook, Mauban, Quezon",
        "male_count": 1,
        "female_count": 1,
        "toilet_type": "none",
        "water_level": "level_1",
        "water_source": "Deep Well",
        "waste_disposal": "dumped",
        "status": "violation",
        "latitude": 14.1838,
        "longitude": 121.7421,
        "remarks": "At-risk household.",
        "last_survey_date": "2026-04-04",
    },
    {
        "household_code": "H-0009",
        "household_head": "Ralph Richmond Amarillo",
        "barangay": "Poblacion",
        "address": "Brgy. Poblacion, Mauban, Quezon",
        "male_count": 2,
        "female_count": 2,
        "toilet_type": "water_sealed",
        "water_level": "level_2",
        "water_source": "Communal Faucet",
        "waste_disposal": "collected",
        "status": "for_completion",
        "latitude": 14.1794,
        "longitude": 121.7229,
        "remarks": "Pending sanitation document completion.",
        "last_survey_date": "2026-04-05",
    },
    {
        "household_code": "H-0010",
        "household_head": "Quert Russel Lalisan",
        "barangay": "San Roque",
        "address": "Brgy. San Roque, Mauban, Quezon",
        "male_count": 3,
        "female_count": 4,
        "toilet_type": "pour_flush",
        "water_level": "level_3",
        "water_source": "LGU Waterworks",
        "waste_disposal": "composted",
        "status": "for_completion",
        "latitude": 14.1946,
        "longitude": 121.7365,
        "remarks": "For completion.",
        "last_survey_date": "2026-04-05",
    },
    {
        "household_code": "H-0011",
        "household_head": "John Joseph Israel",
        "barangay": "Bagong Pook",
        "address": "Brgy. Bagong Pook, Mauban, Quezon",
        "male_count": 4,
        "female_count": 2,
        "toilet_type": "pit_latrine",
        "water_level": "level_1",
        "water_source": "Deep Well",
        "waste_disposal": "burned",
        "status": "good_standing",
        "latitude": 14.1768,
        "longitude": 121.7408,
        "remarks": "Good standing.",
        "last_survey_date": "2026-04-06",
    },
    {
        "household_code": "H-0012",
        "household_head": "Emmanuel Aviles",
        "barangay": "San Roque",
        "address": "Brgy. San Roque, Mauban, Quezon",
        "male_count": 5,
        "female_count": 4,
        "toilet_type": "none",
        "water_level": "level_2",
        "water_source": "Communal Faucet",
        "waste_disposal": "dumped",
        "status": "violation",
        "latitude": 14.1812,
        "longitude": 121.7218,
        "remarks": "Needs priority inspection.",
        "last_survey_date": "2026-04-06",
    },
]
