from django.urls import path

from .auth_views import current_user_view, login_view, logout_view
from .views.shared import (
    activity_log_list,
    bootstrap_data,
    health_check,
    reference_tables,
)
from .views.tourism import (
    arrival_monitoring_data,
    booking_management_data,
    dashboard_data,
    feedback_detail,
    feedback_list,
    online_booking_import,
    reports_data,
    resort_detail,
    resort_list,
    tourist_record_detail,
    tourist_record_list,
)
from .views.sanitation import (
    household_barangay_list,
    household_bootstrap_data,
    household_dashboard_data,
    household_record_detail,
    household_record_list,
    sanitation_bootstrap_data,
    sanitation_business_type_list,
    sanitation_complaint_detail,
    sanitation_complaint_list,
    sanitation_dashboard_data,
    sanitation_establishment_detail,
    sanitation_establishment_list,
    sanitation_inspection_detail,
    sanitation_inspection_list,
    sanitation_permit_data,
    sanitation_renewal_detail,
    sanitation_renewal_list,
    sanitation_report_data,
    sanitation_submission_data,
)
from .views.mobile import (
    mobile_destination_detail,
    mobile_destination_list,
    mobile_feedback_submit,
    mobile_household_survey_submit,
    mobile_sanitation_bootstrap,
    mobile_sanitation_inspection_submit,
    mobile_sanitation_permit_verify,
    mobile_sanitation_report_history,
    mobile_sanitation_report_submit,
    mobile_tourism_bootstrap,
    mobile_tourist_registration,
)

urlpatterns = [
    path("health/", health_check),
    path("auth/login/", login_view),
    path("auth/me/", current_user_view),
    path("auth/logout/", logout_view),
    path("activity-logs/", activity_log_list),
    path("bootstrap/", bootstrap_data),

    # Public mobile app routes
    path("mobile/tourism/bootstrap/", mobile_tourism_bootstrap),
    path("mobile/tourism/destinations/", mobile_destination_list),
    path("mobile/tourism/destinations/<int:resort_id>/", mobile_destination_detail),
    path("mobile/tourism/register-visit/", mobile_tourist_registration),
    path("mobile/tourism/feedback/", mobile_feedback_submit),
    path("mobile/sanitation/bootstrap/", mobile_sanitation_bootstrap),
    path("mobile/sanitation/inspections/", mobile_sanitation_inspection_submit),
    path("mobile/sanitation/reports/", mobile_sanitation_report_submit),
    path("mobile/sanitation/reports/history/", mobile_sanitation_report_history),
    path("mobile/sanitation/permits/verify/", mobile_sanitation_permit_verify),
    path("mobile/sanitation/household-surveys/", mobile_household_survey_submit),

    # Tourism routes
    path("reference-tables/", reference_tables),
    path("booking-management/", booking_management_data),
    path("online-booking-import/", online_booking_import),
    path("arrival-monitoring/", arrival_monitoring_data),
    path("dashboard/", dashboard_data),
    path("reports/", reports_data),
    path("resorts/", resort_list),
    path("resorts/<int:resort_id>/", resort_detail),
    path("feedback/", feedback_list),
    path("feedback/<int:feedback_id>/", feedback_detail),
    path("tourist-records/", tourist_record_list),
    path("tourist-records/<str:survey_id>/", tourist_record_detail),

    # Sanitation routes
    path("sanitation/bootstrap/", sanitation_bootstrap_data),
    path("sanitation/dashboard/", sanitation_dashboard_data),
    path("sanitation/business-types/", sanitation_business_type_list),
    path("sanitation/establishments/", sanitation_establishment_list),
    path("sanitation/establishments/<int:establishment_id>/", sanitation_establishment_detail),
    path("sanitation/inspections/", sanitation_inspection_list),
    path("sanitation/inspections/<int:inspection_id>/", sanitation_inspection_detail),
    path("sanitation/permits/", sanitation_permit_data),
    path("sanitation/renewals/", sanitation_renewal_list),
    path("sanitation/renewals/<int:renewal_id>/", sanitation_renewal_detail),
    path("sanitation/complaints/", sanitation_complaint_list),
    path("sanitation/complaints/<int:complaint_id>/", sanitation_complaint_detail),
    path("sanitation/submissions/", sanitation_submission_data),
    path("sanitation/reports/", sanitation_report_data),

    #Household Routes
    path("households/bootstrap/", household_bootstrap_data),
    path("households/barangays/", household_barangay_list),
    path("households/dashboard/", household_dashboard_data),
    path("households/records/", household_record_list),
    path("households/records/<int:household_id>/", household_record_detail),
]
