from django.urls import path

from .auth_views import current_user_view, login_view, logout_view
from .views import (
    activity_log_list,
    arrival_monitoring_data,
    bootstrap_data,
    booking_management_data,
    dashboard_data,
    feedback_detail,
    feedback_list,
    health_check,
    household_bootstrap_data,
    household_dashboard_data,
    household_record_detail,
    household_record_list,
    reference_tables,
    online_booking_import,
    reports_data,
    resort_detail,
    resort_list,
    sanitation_bootstrap_data,
    sanitation_business_type_list,
    sanitation_complaint_detail,
    sanitation_complaint_list,
    sanitation_dashboard_data,
    sanitation_establishment_detail,
    sanitation_establishment_list,
    sanitation_inspection_detail,
    sanitation_inspection_list,
    sanitation_permit_data,
    sanitation_renewal_detail,
    sanitation_renewal_list,
    sanitation_report_data,
    sanitation_submission_data,
    tourist_record_detail,
    tourist_record_list,
)

urlpatterns = [
    path("health/", health_check),
    path("auth/login/", login_view),
    path("auth/me/", current_user_view),
    path("auth/logout/", logout_view),
    path("activity-logs/", activity_log_list),
    path("bootstrap/", bootstrap_data),

    # Tourism routes
    path("reference-tables/", reference_tables),
    path("booking-management/", booking_management_data),
    path("online-booking-import/", online_booking_import),
    path("arrival-monitoring/", arrival_monitoring_data),
    path("dashboard/", dashboard_data),
    path("reports/", reports_data),
    path("resorts/", resort_list),
    path("resorts/<int:resort_id>/", resort_detail),
    path("feedback/", feedback_list),
    path("feedback/<int:feedback_id>/", feedback_detail),
    path("tourist-records/", tourist_record_list),
    path("tourist-records/<str:survey_id>/", tourist_record_detail),

    # Sanitation routes
    path("sanitation/bootstrap/", sanitation_bootstrap_data),
    path("sanitation/dashboard/", sanitation_dashboard_data),
    path("sanitation/business-types/", sanitation_business_type_list),
    path("sanitation/establishments/", sanitation_establishment_list),
    path("sanitation/establishments/<int:establishment_id>/", sanitation_establishment_detail),
    path("sanitation/inspections/", sanitation_inspection_list),
    path("sanitation/inspections/<int:inspection_id>/", sanitation_inspection_detail),
    path("sanitation/permits/", sanitation_permit_data),
    path("sanitation/renewals/", sanitation_renewal_list),
    path("sanitation/renewals/<int:renewal_id>/", sanitation_renewal_detail),
    path("sanitation/complaints/", sanitation_complaint_list),
    path("sanitation/complaints/<int:complaint_id>/", sanitation_complaint_detail),
    path("sanitation/submissions/", sanitation_submission_data),
    path("sanitation/reports/", sanitation_report_data),

    #Household Routes
    path("households/bootstrap/", household_bootstrap_data),
    path("households/dashboard/", household_dashboard_data),
    path("households/records/", household_record_list),
    path("households/records/<int:household_id>/", household_record_detail),
]
