import os
import sys
import django
import random
from datetime import date, timedelta

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from api.models import (
    TouristRecord, FeedbackEntry, HouseholdSanitationRecord, 
    SanitaryEstablishment, SanitaryPermitRenewal, SanitaryComplaint, SanitaryInspection
)

print("Starting to clean up previous mock data and randomize all existing data...")

# 1. Delete previous mock data generated by the 50-item scripts
SanitaryEstablishment.objects.filter(business_name__startswith="Test Establishment").delete()
HouseholdSanitationRecord.objects.filter(household_code__startswith="HH-2026-").delete()
TouristRecord.objects.filter(survey_id__startswith="SURV-2026-").delete()
FeedbackEntry.objects.filter(message="This is a mock feedback generated for the system.").delete()
SanitaryComplaint.objects.filter(complainant_name__startswith="Citizen ").delete()

print("Deleted previous 50-item mock records.")

# 2. Randomize Tourism Data (TouristRecord)
tourists = list(TouristRecord.objects.all())
print(f"Randomizing {len(tourists)} Tourist Records...")

start_date_tourist = date(2025, 1, 1)
end_date_tourist = date(2026, 6, 30)
tourist_date_range = (end_date_tourist - start_date_tourist).days

for record in tourists:
    # Randomize status: 85% arrived, 10% pending, 5% no_show
    rand = random.random()
    if rand < 0.85:
        record.status = "arrived"
    elif rand < 0.95:
        record.status = "pending"
    else:
        record.status = "no_show"
        
    random_days = random.randint(0, tourist_date_range)
    new_date = start_date_tourist + timedelta(days=random_days)
    
    # Peak season bias: 30% chance to force it into summer (March, April, May)
    if random.random() < 0.3:
        year = random.choice([2025, 2026])
        month = random.choice([3, 4, 5])
        day = random.randint(1, 28)
        new_date = date(year, month, day)
        
    record.arrival_date = new_date

if tourists:
    TouristRecord.objects.bulk_update(tourists, ['status', 'arrival_date'])

# 3. Randomize Sanitary Establishments Data
establishments = list(SanitaryEstablishment.objects.all())
print(f"Randomizing {len(establishments)} Sanitary Establishments...")

start_date_sanitation = date(2025, 1, 1)
end_date_sanitation = date(2026, 12, 31)
sanitation_date_range = (end_date_sanitation - start_date_sanitation).days

for est in establishments:
    # Randomize compliance status
    rand_comp = random.random()
    if rand_comp < 0.60:
        est.compliance_status = "good_standing"
    elif rand_comp < 0.80:
        est.compliance_status = "upcoming"
    elif rand_comp < 0.95:
        est.compliance_status = "for_completion"
    else:
        est.compliance_status = "violation"
        
    # Randomize permit status
    rand_perm = random.random()
    if rand_perm < 0.70:
        est.permit_status = "active"
    elif rand_perm < 0.85:
        est.permit_status = "renewal_due"
    elif rand_perm < 0.95:
        est.permit_status = "conditional"
    else:
        est.permit_status = "suspended"

    random_days_issued = random.randint(0, sanitation_date_range - 365)
    est.permit_issued_date = start_date_sanitation + timedelta(days=random_days_issued)
    est.permit_expiry_date = est.permit_issued_date + timedelta(days=365)

if establishments:
    SanitaryEstablishment.objects.bulk_update(establishments, ['compliance_status', 'permit_status', 'permit_issued_date', 'permit_expiry_date'])

# 4. Generate Sanitary Inspections for the Calendar
print("Generating Sanitary Inspections scattered across the year for the calendar...")
# Clear old mock inspections to prevent duplicate clutter if running multiple times
SanitaryInspection.objects.filter(remarks="Generated for calendar mock data").delete()

# We will create about 300 scattered inspections for the calendar
inspections_to_create = []
if establishments:
    for i in range(300):
        est = random.choice(establishments)
        random_days = random.randint(0, sanitation_date_range)
        inspection_dt = start_date_sanitation + timedelta(days=random_days)
        
        # Calendar usually shows next_due_date or inspection_scheduled_date. Let's provide next_due_date too
        next_due = inspection_dt + timedelta(days=random.choice([30, 90, 180, 365]))
        
        inspections_to_create.append(SanitaryInspection(
            establishment=est,
            inspector_name=f"Inspector {random.randint(1, 10)}",
            inspection_date=inspection_dt,
            next_due_date=next_due,
            findings="Routine check passed." if random.random() > 0.3 else "Minor issues found, for completion.",
            remarks="Generated for calendar mock data",
            status_after_inspection=random.choice(["good_standing", "for_completion", "violation"]),
            is_draft=False
        ))
        
    SanitaryInspection.objects.bulk_create(inspections_to_create)

print("Data cleanup and randomization completed successfully!")
